export const RECEIVE_DASH_PLAYER = 'RECEIVE_DASH_PLAYER';
export const CHANGE_PAGE_DASH_PLAYER = 'CHANGE_PAGE_DASH_PLAYER';
export const SORT_ORDER_DASH_PLAYER = 'SORT_ORDER_DASH_PLAYER';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
